# -* encoding: utf-8 *-
import argparse

from gopythongo.utils import CommandLinePlugin


class BaseAssembler(CommandLinePlugin):
    def __init__(self, *args, **kwargs) -> None: ...

    @property
    def assembler_name(self) -> str: ...
    def assemble(self, args: argparse.Namespace): ...


def add_args(parser: argparse.ArgumentParser) -> None: ...
def validate_args(args: argparse.Namespace) -> None: ...
def assemble(args: argparse.Namespace) -> None: ...

