# -* encoding: utf-8 *-
import argparse

from gopythongo.utils import CommandLinePlugin


class BaseStore(CommandLinePlugin):
    def __init__(self, *args, **kwargs) -> None: ...

    @property
    def store_name(self) -> str: ...
    def store(self, args: argparse.Namespace): ...


def add_args(parser: argparse.ArgumentParser) -> None: ...
def validate_args(args: argparse.Namespace) -> None: ...
def store(args: argparse.Namespace) -> None: ...
