# -* encoding: utf-8 *-
import argparse
from typing import Tuple, List

from gopythongo.utils import CommandLinePlugin


class BaseBuilder(CommandLinePlugin):
    def __init__(self, *args, **kwargs) -> None: ...

    @property
    def builder_name(self) -> str: ...
    def build(self, args: argparse.Namespace): ...


def test_gopythongo(path: str) -> Tuple[str, List[str]]: ...
def add_args(parser: argparse.ArgumentParser) -> None: ...
def validate_args(args: argparse.Namespace) -> None: ...
def build(args: argparse.Namespace) -> None: ...
