# -* encoding: utf-8 *-
import argparse
from typing import List


def init_color(no_color: bool): ...
def create_script_path(virtualenv_path: str, script_name: str) -> str: ...
def flatten(x: List) -> List: ...


class GoPythonGoEnableSuper(object):
    def __init__(self, *args, **kwargs) -> None: ...


class CommandLinePlugin(GoPythonGoEnableSuper):
    def __init__(self, *args, **kwargs) -> None: ...

    def add_args(self, parser: argparse.ArgumentParser): ...
    def validate_args(self, args: argparse.Namespace): ...
