# -* encoding: utf-8 *-

# Type stub for gopythongo.utils.debversion so we're Python2 compatible
from typing import Tuple, List


def debian_substr_compare(a: str, b: str) -> int: ...


def split_version_parts(version_str: str, version_re: str) -> List[str]: ...


def debian_versionpart_compare(mine: str, theirs: str) -> int: ...


class DebianVersion(object):
    def __init__(self, epoch: str, version: str, revision: str) -> None: ...

    @staticmethod
    def fromstring(version_str: str) -> 'DebianVersion': ...

    def as_tuple(self) -> Tuple[str, str, str]: ...

    def __lt__(self, other: 'DebianVersion') -> bool: ...

    def __eq__(self, other: 'DebianVersion') -> bool: ...

    def tostring(self) -> str: ...
