# -* encoding: utf-8 *-

# Type stub for gopythongo.utils.debversion so we're Python2 compatible
from typing import Tuple, List, Union, Any


def debian_substr_compare(a: str, b: str) -> int: ...


def split_version_parts(version_str: str, version_re: str) -> List[str]: ...


def debian_versionpart_compare(mine: List[str], theirs: List[str]) -> int: ...


class InvalidDebianVersionString(Exception): ...


class DebianVersion(object):
    def __init__(self, epoch: str, version: str, revision: str) -> None: ...

    def validate(self) -> None: ...

    @classmethod
    def fromstring(cls, version_str: str) -> 'DebianVersion': ...

    def as_tuple(self) -> Tuple[str, str, str]: ...

    def __lt__(self, other: 'DebianVersion') -> bool: ...

    def __eq__(self, other: Union['DebianVersion', Any, None]) -> bool: ...

    def tostring(self) -> str: ...
