# -* encoding: utf-8 *-
import argparse
from typing import List

from gopythongo.utils import CommandLinePlugin
from gopythongo.versioners.parsers import VersionContainer


class BaseVersioner(CommandLinePlugin):
    def __init__(self, *args, **kwargs) -> None: ...

    @property
    def versioner_name(self) -> str: ...

    @property
    def can_read(self) -> bool: ...

    @property
    def can_create(self) -> bool: ...

    @property
    def operates_on(self) -> List[str]: ...

    def print_help(self) -> None: ...
    def read(self, args: argparse.Namespace) -> str: ...
    def create(self, args: argparse.Namespace) -> str: ...
    def execute_action(self, version: VersionContainer, action: str) -> VersionContainer: ...


def add_args(parser: argparse.ArgumentParser) -> None: ...
def validate_args(args: argparse.Namespace) -> None: ...
def version(args: argparse.Namespace) -> None: ...
