FROM debian:jessie

WORKDIR /
RUN apt-get update && apt-get -q -y -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-confdef install {{" ".join(dependencies["debian/jessie"])}}
{% for cmd in run_after_create %}
ADD {{cmd}} {{cmd}}
RUN {{cmd}}
{% endfor %}
