# -* encoding: utf-8 *-
import argparse

from gopythongo.utils import CommandLinePlugin


class BasePacker(CommandLinePlugin):
    def __init__(self, *args, **kwargs) -> None: ...

    @property
    def packer_name(self) -> str: ...
    def pack(self, args) -> None: ...


def add_args(parser: argparse.ArgumentParser) -> None: ...
def validate_args(args: argparse.Namespace) -> None: ...
def pack(args: argparse.Namespace) -> None: ...
