# -* encoding: utf-8 *-
import argparse
from typing import Tuple

from gopythongo.utils import GoPythonGoEnableSuper, CommandLinePlugin


class UnknownParserName(Exception):
    pass


class UnconvertableVersion(Exception):
    pass


class VersionContainer(GoPythonGoEnableSuper):
    def __init__(self, version, parsed_by) -> None: ...
    def convert_to(self, parsername: str) -> 'VersionContainer': ...
    def perform_action(self, action: str) -> None: ...


class BaseVersionParser(CommandLinePlugin):
    def __init__(self, *args, **kwargs) -> None: ...

    @property
    def versionparser_name(self) -> str: ...
    def print_help(self) -> None: ...
    def parse(self, version_str: str, args: argparse.Namespace) -> VersionContainer: ...
    def can_convert_from(self, parserid: str) -> Tuple[bool, bool]: ...
    def can_convert_to(self, parserid: str) -> Tuple[bool, bool]: ...
    def convert_from(self, version: VersionContainer) -> VersionContainer: ...
    def convert_to(self, version: VersionContainer, parserid: str) -> VersionContainer: ...
